dist: xenial

language: go

go: 
  - 1.11.x


before_install:
  - sudo add-apt-repository -y ppa:asiffer/libspot
  - sudo apt-get update
  - sudo apt-get install -y libspot
  - go get -v github.com/rainycape/dl
  - go get -v github.com/rs/zerolog
  - go get -v github.com/modocache/gover

script:
  - go test -v ./...
  # Collect coverage reports
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -i sh -c {}
  # Merge coverage reports
  - gover . coverprofile.txt

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverprofile.txt
