dist: xenial

language: go

go:
- 1.11.x
- master

before_install:
- sudo add-apt-repository -y ppa:asiffer/libspot
- sudo apt-get update
- sudo apt-get install -y libspot
- go get -v github.com/rainycape/dl
- go get -v github.com/rs/zerolog

script:
  - go test -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)